# Generated by Django 2.2.4 on 2019-08-23 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('title_en', models.CharField(max_length=10)),
                ('audience', models.IntegerField()),
                ('open_date', models.DateTimeField(auto_now_add=True)),
                ('genre', models.CharField(max_length=10)),
                ('watch_grade', models.CharField(max_length=10)),
                ('score', models.FloatField()),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
